# Config file for the akshara kibana setup
#
# We use containers so if you are upgrading kibana, make sure that we
# carry over the configs from image default:
# https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana-x-pack.yml

server.name: akshara-kibana
server.host: "0"

elasticsearch.url: http://elasticsearch:9200
#elasticsearch.username: elastic
#elasticsearch.password: changeme

# Kibana specific xpack features
xpack.monitoring.enabled: true
xpack.reporting.enabled: true
# paid features
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.security.enabled: false

xpack.monitoring.ui.container.elasticsearch.enabled: true
