version: '3.6'

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        # version is picked up from the .env file
        - es_version=${ES_VERSION}
    image: akshara/elasticsearch:${ES_VERSION}
    container_name: akshara_elasticsearch
    environment:
      - cluster.name=akshara-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      # based on how much memory a node has
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: akshara_kibana
    ports:
      - 5601:5601
    networks:
      - esnet
volumes:
  esdata:
    driver: local
networks:
  esnet:
