version: '3.1'

services:

  elasticsearch:
    image: elasticsearch
    volumes:
        - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana
    ports:
      - 5601:5601
