version: '3.6'
services:
  sonic:
    # the vars here are picked up from the .env file
    image: valeriansaliou/sonic:v${SONIC_VERSION}
    container_name: akshara_sonic
    volumes:
      # share the config in the repo with the container
      - ./sonic/config/sonic.cfg:/etc/sonic.cfg
      # using local docker volume for sonic data
      # gets stored in /var/lib/docker/volumes by default, and can specify a
      # custom path here, but need to configure the dir perms for container use
      - sonicdata:/var/lib/sonic/store
    ports:
      - 1491:1491
    networks:
      - sonicnet
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        # the vars here are picked up from the .env file
        - es_image=${ES_IMAGE}
        - es_version=${ES_VERSION}
    image: akshara/${ES_IMAGE}:${ES_VERSION}
    container_name: akshara_elasticsearch
    environment:
      # also set the vm.max_map_count kernel setting for production use. See:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
      - "ES_JAVA_OPTS=-Xms${ES_JAVA_HEAP_SIZE} -Xmx${ES_JAVA_HEAP_SIZE}"
      # elasticsearch-specific xpack features (to be used when xpack is installed)
      # disable these when using the elasticsearch-oss image
      - xpack.license.self_generated.type=basic
      - xpack.monitoring.enabled=true
      # default is 7 days. Enable if we run short of disk space
      #- xpack.monitoring.history.duration=3d
      # paid features
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      # disabling swapping for performance and node stability
      memlock:
        soft: -1
        hard: -1
    volumes:
      # share the config in the repo with the container
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/stopwords:/usr/share/elasticsearch/config/stopwords
      # using local docker volume for es data
      # gets stored in /var/lib/docker/volumes by default, and can specify a
      # custom path here, but need to configure the dir perms for container use
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/${KIBANA_IMAGE}:${KIBANA_VERSION}
    container_name: akshara_kibana
    environment:
      # limit kibana memory usage (default is 1G)
      - "NODE_OPTIONS=--max-old-space-size=${KIBANA_NODE_MEM_LIMIT_MB}"
      # for valid options here, see:
      # https://github.com/elastic/kibana-docker/blob/master/build/kibana/bin/kibana-docker
      # if true, only error messages are shown
      - LOGGING_QUIET=${KIBANA_LOGGING_QUIET}
      # which page to launch by default
      - KIBANA_DEFAULTAPPID=discover
      # kibana-specific xpack features (to be used when xpack is installed)
      - XPACK_LICENSE_SELF_GENERATED_TYPE=basic
      # overriding the xpack defaults currently triggers optimizing and caching of kibana bundles,
      # which takes forever. Disabling these and going with the defaults here.
      #- XPACK_MONITORING_ENABLED=true
      #- XPACK_REPORTING_ENABLED=true
      # paid features
      #- XPACK_GRAPH_ENABLED=false
      #- XPACK_ML_ENABLED=false
      #- XPACK_SECURITY_ENABLED=false
    ports:
      - 5601:5601
    networks:
      - esnet
  frontend:
    build: ./parijat-frontend
    container_name: parijat_frontend
    ports:
      - 8080:8080
    networks:
      - esnet
volumes:
  esdata:
    driver: local
  sonicdata:
    driver: local
networks:
  esnet:
  sonicnet:
